lua: fix compilation
Include unistd.h to fix the following error.

----
  CC       liblua_plugin_la-intf.lo
  intf.c: In function 'Start_LuaIntf':
  intf.c:372: error: implicit declaration of function 'close'
----

Signed-off-by: Rafaël Carré <funman@videolan.org>
(cherry picked from commit 6eb6e32d5a52deb92ce25dd8245510e216c3edaf)

Signed-off-by: KO Myung-Hun <komh@chollian.net>
Signed-off-by: Rafaël Carré <funman@videolan.org>